### ISSUE TITLE
Wrong tooltip placement on page change

### ISSUE THREAD

**Issue by danieluct** [microsoft/powerbi-visuals-utils-tooltiputils#39] opened 2020-05-06 14:00 UTC
Hi,
I have a custom visual that uses the provided tooltip utils. Unfortunately, when changing pages on app.powerbi.com, the tooltip stops showing at the correct position, and is instead placed in the upper left left corner of the web page. Going through the un-uglified code, I noticed that there seems to be an issue with the internal value "scale" being undefined. Changing slicers and even resizing the browser window seems to solve it.
The specific code (in https://app.powerbi.com/13.0.13035.262/scripts/powerbiportal.common.bundle.min.js ) is `fixCoordinates = function(e) {
                if (/Edge\/\d./i.test(navigator.userAgent) && $("body.fullScreen").length > 0)
                    return e;
                var t = this.element.offset();
                return e[0] = e[0] * this.scale + t.left,
                e[1] = e[1] * this.scale + t.top,
                e
            }`

**Comment by marthaav** [comment] 2020-05-14 01:09
Not sure what is being said here. I cannot change js script in PBI Services (that is in the cloud). The bullet chart, drill through function works well in Desktop, but does not work in the cloud. This is a bug right? Will it be fixed? Does the drill through feature work for anybody out there when running in PBI Services?

**Comment by FinRR** [comment] 2020-05-27 06:58
Hi,
One more problem. If you disable tooltips for Bullet Chart, they still appear in the iOS mobile version and interfere with viewing, but everything works correctly in the browser.

**Comment by kouvel** [comment] 2020-06-23 16:08
@helen508light you probably meant to assign someone else (typo?)

**Comment by helen508light** [comment] 2020-06-29 18:36
This issue was fixed for Desktop, but still in works for PBI Services and PBI Desktop Report Server

**Comment by helen508light** [comment] 2020-07-03 17:37
This is duplicate of https://github.com/microsoft/PowerBI-visuals/issues/605

**Closed by helen508light** 2020-07-03 17:37 UTC
Labels: bug
